# 第7章 テスト

### 7.6.2　panderaを使ったデータ検証

In [8]:
## import pandera as pa
import pandera.pandas as pa

import pandas as pd

In [16]:
import pandera.pandas as pa

schema = pa.DataFrameSchema({
    "Year": pa.Column(int), # ❶
    "India": pa.Column(float), # ❷
    "United States of America": pa.Column(float) # ❸
})

In [17]:
schema(df)

    Year  India  United States of America
0   2000   9.02                     13.33
1   2001   9.01                     14.02
2   2002   8.84                     14.02
3   2003   8.84                     14.25
4   2004   8.84                     14.25
5   2005   8.29                     14.94
6   2006   8.26                     15.17
7   2007   8.26                     16.32
8   2008   9.06                     16.78
9   2009   9.06                     17.01
10  2010  10.83                     16.78
11  2011  10.83                     16.78
12  2012  11.01                     16.82
13  2013  11.01                     17.78
14  2014  11.38                     18.29
15  2015  11.97                     19.35
16  2016  11.97                     19.35
17  2017  11.81                     19.08
18  2018  11.81                     19.49
19  2019  12.60                     23.56
20  2020  14.36                     23.43
21  2021  14.44                     27.25
22  2022  14.94                     27.71
23  2023  15.13                     29.43

In [20]:
schema = pa.DataFrameSchema({
    "Year": pa.Column(int, checks=pa.Check.in_range(2000, 2023)),
    "India": pa.Column(float, checks=pa.Check.in_range(0, 100)),
    "United States of America": pa.Column(float, checks=pa.Check.in_range(0, 100))
})

In [21]:
print(schema)

<Schema DataFrameSchema(
    columns={
        'Year': <Schema Column(name=Year, type=DataType(int64))>
        'India': <Schema Column(name=India, type=DataType(float64))>
        'United States of America': <Schema Column(name=United States of America, type=DataType(float64))>
    },
    checks=[],
    parsers=[],
    coerce=False,
    dtype=None,
    index=None,
    strict=False,
    name=None,
    ordered=False,
    unique_column_names=False,
    metadata=None,
    add_missing_columns=False
)>

In [22]:
from pydantic import BaseModel
from typing import Optional
from datetime import datetime

class CountryData(BaseModel):
    country_name: str # ❶
    population: int # ❷
    literacy_rate_2020: Optional[float] # ❸
    timestamp: Optional[datetime] = None # ❹

In [24]:
sample_data_correct = {
    'country_name': 'India',
    'population': 1417242151,
    'literacy_rate_2020': 79.43,
    'timestamp': datetime.now()
}

In [25]:
india = CountryData(**sample_data_correct)

In [26]:
india.timestamp

datetime.datetime(2025, 5, 17, 12, 41, 8, 782618)

In [27]:
sample_data_incorrect = {
    'country_name': 'United States',
    'population': None,
    'literacy_rate_2020': None,
    'timestamp': None
}

united_states = CountryData(**sample_data_incorrect)

ValidationError: 1 validation error for CountryData
population
  Input should be a valid integer [type=int_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.6/v/int_type

In [9]:
df = pd.read_csv("../data/women_in_parliament_processed.csv")
df = df.rename(
    columns={
        "Unnamed: 0": "Year",
    }
)

In [10]:
df = df[["Year", "India", "United States of America"]]

In [11]:
df.head()

   Year  India  United States of America
0  2000   9.02                     13.33
1  2001   9.01                     14.02
2  2002   8.84                     14.02
3  2003   8.84                     14.25
4  2004   8.84                     14.25

In [12]:
schema = pa.DataFrameSchema(
    {
        "Year": pa.Column(int),
        "India": pa.Column(float),
        "United States of America": pa.Column(float),
    }
)

In [13]:
schema(df)

    Year  India  United States of America
0   2000   9.02                     13.33
1   2001   9.01                     14.02
2   2002   8.84                     14.02
3   2003   8.84                     14.25
4   2004   8.84                     14.25
5   2005   8.29                     14.94
6   2006   8.26                     15.17
7   2007   8.26                     16.32
8   2008   9.06                     16.78
9   2009   9.06                     17.01
10  2010  10.83                     16.78
11  2011  10.83                     16.78
12  2012  11.01                     16.82
13  2013  11.01                     17.78
14  2014  11.38                     18.29
15  2015  11.97                     19.35
16  2016  11.97                     19.35
17  2017  11.81                     19.08
18  2018  11.81                     19.49
19  2019  12.60                     23.56
20  2020  14.36                     23.43
21  2021  14.44                     27.25
22  2022  14.94                     27.71
23  2023  15.13                     29.43

In [14]:
schema = pa.DataFrameSchema(
    {
        "Year": pa.Column(int, checks=pa.Check.in_range(2000, 2023)),
        "India": pa.Column(float, checks=pa.Check.in_range(0, 100)),
        "United States of America": pa.Column(float, checks=pa.Check.in_range(0, 100)),
    }
)

In [15]:
schema(df)

    Year  India  United States of America
0   2000   9.02                     13.33
1   2001   9.01                     14.02
2   2002   8.84                     14.02
3   2003   8.84                     14.25
4   2004   8.84                     14.25
5   2005   8.29                     14.94
6   2006   8.26                     15.17
7   2007   8.26                     16.32
8   2008   9.06                     16.78
9   2009   9.06                     17.01
10  2010  10.83                     16.78
11  2011  10.83                     16.78
12  2012  11.01                     16.82
13  2013  11.01                     17.78
14  2014  11.38                     18.29
15  2015  11.97                     19.35
16  2016  11.97                     19.35
17  2017  11.81                     19.08
18  2018  11.81                     19.49
19  2019  12.60                     23.56
20  2020  14.36                     23.43
21  2021  14.44                     27.25
22  2022  14.94                     27.71
23  2023  15.13                     29.43